FROM postgres:latest

RUN apt-get update && apt-get install --no-install-recommends -y \
  openssh-server \
  && rm -rf /var/lib/apt/lists/*

COPY ./app /home/app
WORKDIR /home/app
RUN ./foobob_script.sh
RUN service ssh restart